# Generated by Django 3.2.4 on 2021-06-21 08:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Residential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('floor_number', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('furnishing', models.CharField(max_length=100)),
                ('car_parking', models.IntegerField(default=0)),
                ('carpet_area', models.IntegerField()),
                ('super_area', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(default='default.jfif', upload_to='property_images/residential')),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('floors_allowed_for_construction', models.IntegerField()),
                ('number_of_openside', models.IntegerField()),
                ('width_of_road_facing_the_plot', models.IntegerField()),
                ('boundry_wall_status', models.CharField(max_length=100)),
                ('plot_area', models.IntegerField()),
                ('plot_length', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('photo_main', models.ImageField(default='default.jfif', upload_to='property_images/plot')),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_PG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('monthly_rent', models.IntegerField()),
                ('security_deposit', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('balconies', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('furnishing', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(default='default.jfif', upload_to='property_images/pg')),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Property_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/sub_images')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Property_Commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_for', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('locality', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('landzone', models.CharField(max_length=200)),
                ('ideal_for_business', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('floor_number', models.IntegerField()),
                ('total_floor', models.IntegerField()),
                ('washrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('personal_washrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('furnishing', models.CharField(max_length=100)),
                ('cafeteria', models.CharField(max_length=100)),
                ('carpet_area', models.IntegerField()),
                ('super_area', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
                ('photo_main', models.ImageField(default='default.jfif', upload_to='property_images/commercial')),
                ('date_posted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
