# Generated by Django 3.2.4 on 2021-06-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20210621_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_commercial',
            name='property_type',
            field=models.CharField(default='Commercial', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property_pg',
            name='property_type',
            field=models.CharField(default='PG', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property_plot',
            name='property_type',
            field=models.CharField(default='Plot', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='property_residential',
            name='property_type',
            field=models.CharField(default='Residential', editable=False, max_length=100),
        ),
    ]
