# Generated by Django 3.2.4 on 2021-06-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20210622_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property_residential',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
