# Generated by Django 3.2.4 on 2021-06-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_property_residential_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property_pg',
            name='property_for',
            field=models.CharField(default='PG', editable=False, max_length=100),
        ),
    ]
